### ISSUE TITLE
bitmask module should be imported from astropy.nddate.bitmask

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/hlapipeline#77]
This module

https://github.com/spacetelescope/hlapipeline/blob/master/hlapipeline/utils/bitmask.py

and where (if?) it is imported anywhere in the package should use

```
from astropy.nddata.bitmask import interpret_bit_flags
```

This has been available since `astropy 3.1`.

**Comment by stsci-hack** [comment]
This package has been deprecated in favor of the software which has been developed and added to the [hlautils sub-package in the Drizzlepac package](https://github.com/spacetelescope/drizzlepac/tree/master/drizzlepac/hlautils).
